// client/src/hooks/useOperators.ts
import { useState, useEffect } from 'react';
// Import the static list generated by your sync script
import { OPERATORS as STATIC_OPERATORS, type Operator } from '../shared/operatorList';

export function useOperators(countryCode?: string) {
  const [operators, setOperators] = useState<Operator[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const [usingFallback, setUsingFallback] = useState(false);

  useEffect(() => {
    const fetchOperators = async () => {
      if (!countryCode) return;
      
      setLoading(true);
      try {
        // 1. Try Live API
        const response = await fetch(`http://localhost:5000/api/operators?country=${countryCode}`);
        if (!response.ok) throw new Error('API Error');
        const data = await response.json();
        setOperators(data);
        setUsingFallback(false);
      } catch (err) {
        // 2. Fallback to Local File
        console.warn('⚠️ API Offline. Using local operator list.');
        const filtered = STATIC_OPERATORS.filter(op => op.countryCode === countryCode);
        setOperators(filtered);
        setUsingFallback(true);
      } finally {
        setLoading(false);
      }
    };

    fetchOperators();
  }, [countryCode]);

  return { operators, loading, usingFallback };
}
