"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const path_1 = __importDefault(require("path")); // 👈 Import path
const dtone_1 = require("./dtone");
const sync_countries_1 = require("./scripts/sync-countries");
const sync_operators_1 = require("./scripts/sync-operators");
const payment_1 = require("./payment");
const app = (0, express_1.default)();
// 🚀 DYNAMIC PORT
const PORT = process.env.PORT || 5000;
app.use((0, cors_1.default)());
app.use(express_1.default.json());
// ==================================================================
// 🚀 CACHE SYSTEM
// ==================================================================
let COUNTRY_CACHE = [];
let OPERATOR_CACHE = [];
const initializeCache = async () => {
    console.log('[Server] ⏳ Initializing Caches...');
    const countries = await (0, sync_countries_1.syncCountries)();
    if (countries)
        COUNTRY_CACHE = countries;
    const operators = await (0, sync_operators_1.syncOperators)();
    if (operators)
        OPERATOR_CACHE = operators;
    console.log(`[Server] 🚀 System Ready! Countries: ${COUNTRY_CACHE.length}, Operators: ${OPERATOR_CACHE.length}`);
};
initializeCache();
setInterval(() => {
    console.log('[Server] ⏰ Running Daily Maintenance...');
    (0, sync_countries_1.syncCountries)().then(d => { if (d)
        COUNTRY_CACHE = d; });
    (0, sync_operators_1.syncOperators)().then(d => { if (d)
        OPERATOR_CACHE = d; });
}, 1000 * 60 * 60 * 24);
// ==================================================================
// API ROUTES
// ==================================================================
app.get('/api/countries', (req, res) => {
    return res.json(COUNTRY_CACHE);
});
app.get('/api/operators', (req, res) => {
    const { country } = req.query;
    if (country) {
        const filtered = OPERATOR_CACHE.filter(op => op.countryCode === String(country).toUpperCase());
        return res.json(filtered);
    }
    return res.json(OPERATOR_CACHE);
});
app.post('/api/create-payment-intent', async (req, res) => {
    const { amount, currency } = req.body;
    if (!amount || !currency)
        return res.status(400).json({ error: 'Amount and currency are required' });
    try {
        const result = await payment_1.paymentService.createPaymentIntent(amount, currency);
        res.json(result);
    }
    catch (error) {
        res.status(500).json({ error: error.message });
    }
});
app.post('/api/lookup', async (req, res) => {
    const { mobile } = req.body;
    if (!mobile)
        return res.status(400).json({ error: 'Mobile number is required' });
    try {
        const result = await dtone_1.dtoneService.lookupMobileNumber(mobile);
        if (!result.success) {
            return res.status(404).json({ error: result.error, code: result.code });
        }
        return res.json(result.data);
    }
    catch (error) {
        return res.status(500).json({ error: error.message });
    }
});
app.post('/api/products', async (req, res) => {
    const { operatorId } = req.body;
    if (!operatorId)
        return res.status(400).json({ error: 'Operator ID is required' });
    try {
        const result = await dtone_1.dtoneService.getProductsForOperator(operatorId);
        if (!result.success) {
            return res.status(400).json({ error: result.error, code: result.code });
        }
        return res.json(result.data);
    }
    catch (error) {
        return res.status(500).json({ error: error.message });
    }
});
app.post('/api/purchase', async (req, res) => {
    const { productId, mobile, amount, unit } = req.body;
    if (!productId || !mobile)
        return res.status(400).json({ error: 'Missing fields' });
    try {
        const result = await dtone_1.dtoneService.purchaseProduct(productId, mobile, amount || 0, unit);
        if (!result.success) {
            return res.status(400).json({ error: result.error, code: result.code });
        }
        return res.json(result.data);
    }
    catch (error) {
        return res.status(500).json({ error: error.message });
    }
});
// ==================================================================
// 📂 SERVE REACT FRONTEND (MUST BE LAST)
// ==================================================================
// 1. Serve static files from the 'dist' folder (generated by 'npm run build')
// Note: We go up one level (..) because Routes.ts is in /server/
app.use(express_1.default.static(path_1.default.join(__dirname, '../dist')));
// 2. Handle React Routing (SPA)
// If a request doesn't match an API route, send back index.html
app.get('*', (req, res) => {
    res.sendFile(path_1.default.join(__dirname, '../dist/index.html'));
});
app.listen(PORT, () => {
    console.log(`🚀 API Server running on port ${PORT}`);
});
