import fs from 'fs';
import path from 'path';

// CONFIGURATION
const API_URL = 'http://localhost:5000/api/countries';

// Resolve path: server/scripts/ -> server/ -> root/ -> client/src/shared/countryValidator.ts
const TARGET_FILE = path.join(__dirname, '../../client/src/shared/countryValidator.ts');

async function generateValidator() {
  console.log('\n🔄 SYNCING COUNTRIES...');
  console.log(`   Source: ${API_URL}`);
  console.log(`   Target: ${TARGET_FILE}`);

  try {
    // 1. Fetch live data from your running API
    const response = await fetch(API_URL);
    
    if (!response.ok) {
      throw new Error(`API Error ${response.status}: Ensure server/Routes.ts is running!`);
    }

    const countries = await response.json();
    console.log(`   ✅ Fetched ${countries.length} supported countries from DTOne.`);

    // 2. Format the TypeScript content
    // We strictly type the interface and inject the JSON data
    const fileContent = `/**
 * AUTO-GENERATED FILE
 * Generated by: server/scripts/generate-validator.ts
 * Timestamp: ${new Date().toISOString()}
 * * This file contains the snapshot of currently supported DTOne countries.
 */

export interface Country {
  name: string;
  code: string;     // ISO2 (e.g. US)
  iso3: string;     // ISO3 (e.g. USA)
  dialCode: string;
}

/**
 * LIVE LIST FROM DTONE
 */
export const COUNTRIES: Country[] = ${JSON.stringify(countries, null, 2)};

/**
 * Gets all available countries sorted alphabetically
 */
export const getAllCountries = (): Country[] => {
  return [...COUNTRIES].sort((a, b) => a.name.localeCompare(b.name));
};

/**
 * Filters countries based on search query (Name, Code, ISO3, or Dial Code)
 */
export const filterCountries = (query: string): Country[] => {
  if (!query) return getAllCountries();
  
  const searchTerm = query.toLowerCase();
  
  return COUNTRIES.filter(country =>
    country.name.toLowerCase().includes(searchTerm) ||
    country.code.toLowerCase().includes(searchTerm) ||
    (country.iso3 && country.iso3.toLowerCase().includes(searchTerm)) ||
    country.dialCode.includes(searchTerm)
  );
};

/**
 * Finds a country by its ISO2 code
 */
export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find(country => country.code === code);
};

/**
 * Validates if a country code is supported
 */
export const isCountrySupported = (code: string): boolean => {
  return COUNTRIES.some(country => country.code === code);
};
`;

    // 3. Write to file
    fs.writeFileSync(TARGET_FILE, fileContent);
    console.log('   🎉 SUCCESS: countryValidator.ts updated!');

  } catch (error: any) {
    console.error('\n❌ SYNC FAILED:', error.message);
    if (error.cause && error.cause.code === 'ECONNREFUSED') {
      console.error('   Hint: Is your backend running on port 5000?');
    }
  }
}

generateValidator();
